# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: isalive.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\risalive.proto\x12\x06\x63ommon\"\x10\n\x0eIsAliveRequest\"b\n\x0fIsAliveResponce\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x11\n\tstartedAt\x18\x03 \x01(\t\x12\x0b\n\x03\x65nv\x18\x04 \x01(\t\x12\x10\n\x08hostname\x18\x05 \x01(\t2H\n\nMonitoring\x12:\n\x07IsAlive\x12\x16.common.IsAliveRequest\x1a\x17.common.IsAliveResponceB\x1b\xaa\x02\x18Lykke.HftApi.ApiContractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'isalive_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030Lykke.HftApi.ApiContract'
  _globals['_ISALIVEREQUEST']._serialized_start=25
  _globals['_ISALIVEREQUEST']._serialized_end=41
  _globals['_ISALIVERESPONCE']._serialized_start=43
  _globals['_ISALIVERESPONCE']._serialized_end=141
  _globals['_MONITORING']._serialized_start=143
  _globals['_MONITORING']._serialized_end=215
# @@protoc_insertion_point(module_scope)
