# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\nhft.common\"\x9b\x01\n\x05\x45rror\x12#\n\x04\x63ode\x18\x01 \x01(\x0e\x32\x15.hft.common.ErrorCode\x12\x0f\n\x07message\x18\x02 \x01(\t\x12-\n\x06\x66ields\x18\x03 \x03(\x0b\x32\x1d.hft.common.Error.FieldsEntry\x1a-\n\x0b\x46ieldsEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01*\x94\x05\n\tErrorCode\x12\x0b\n\x07success\x10\x00\x12\x11\n\x0cruntimeError\x10\xe9\x07\x12\x11\n\x0citemNotFound\x10\xcc\x08\x12\x11\n\x0cinvalidField\x10\xcd\x08\x12\x14\n\x0f\x61\x63tionForbidden\x10\xce\x08\x12\x11\n\x0cmeBadRequest\x10\xd0\x0f\x12\x11\n\x0cmeLowBalance\x10\xd1\x0f\x12\x17\n\x12meAlreadyProcessed\x10\xd2\x0f\x12\x14\n\x0fmeDisabledAsset\x10\xd3\x0f\x12\x13\n\x0emeUnknownAsset\x10\xd4\x0f\x12\x12\n\rmeNoLiquidity\x10\xd5\x0f\x12\x15\n\x10meNotEnoughFunds\x10\xd6\x0f\x12\x0b\n\x06meDust\x10\xd7\x0f\x12&\n!meReservedVolumeHigherThanBalance\x10\xd8\x0f\x12\x0f\n\nmeNotFound\x10\xd9\x0f\x12\x1f\n\x1ameBalanceLowerThanReserved\x10\xda\x0f\x12\x1b\n\x16meLeadToNegativeSpread\x10\xdb\x0f\x12\x15\n\x10meTooSmallVolume\x10\xdc\x0f\x12\x11\n\x0cmeInvalidFee\x10\xdd\x0f\x12\x13\n\x0emeInvalidPrice\x10\xde\x0f\x12\x0f\n\nmeReplaced\x10\xdf\x0f\x12\x17\n\x12meNotFoundPrevious\x10\xe0\x0f\x12\x10\n\x0bmeDuplicate\x10\xe1\x0f\x12\x1c\n\x17meInvalidVolumeAccuracy\x10\xe2\x0f\x12\x1b\n\x16meInvalidPriceAccuracy\x10\xe3\x0f\x12\x14\n\x0fmeInvalidVolume\x10\xe4\x0f\x12\x1c\n\x17meTooHighPriceDeviation\x10\xe5\x0f\x12\x18\n\x13meInvalidOrderValue\x10\xe6\x0f\x12\x0e\n\tmeRuntime\x10\xe7\x0f\x42\x1b\xaa\x02\x18Lykke.HftApi.ApiContractb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'\252\002\030Lykke.HftApi.ApiContract'
  _ERROR_FIELDSENTRY._options = None
  _ERROR_FIELDSENTRY._serialized_options = b'8\001'
  _globals['_ERRORCODE']._serialized_start=187
  _globals['_ERRORCODE']._serialized_end=847
  _globals['_ERROR']._serialized_start=29
  _globals['_ERROR']._serialized_end=184
  _globals['_ERROR_FIELDSENTRY']._serialized_start=139
  _globals['_ERROR_FIELDSENTRY']._serialized_end=184
# @@protoc_insertion_point(module_scope)
